@startuml
skinparam dpi 150
skinparam classAttributeIconSize 0
skinparam classFontSize 10
skinparam classFontName Courier
skinparam wrapWidth 100
top to bottom direction
skinparam linetype ortho

class Database {
}

class AgendamentoTerminalHandler {
  +criar()
  +cancelar()
  +listar()
  +menu()
  +atualizarStatus()
}

class CategoriaDespesaTerminalHandler {
  +criar()
  +remover()
  +atualizar()
  +listar()
  +menu()
}

class ClienteTerminalHandler {
  +criar()
  +remover()
  +atualizar()
  +listar()
  +buscar()
  +menu()
}

class ColaboradorTerminalHandler {
  +listarAdministradores()
  +listarFuncionarios()
  +criarFuncionario()
  +criarAdministrador()
  +menu()
  +atualizarAdministrador()
  +removerAdministrador()
  +atualizarFuncionario()
  +removerFuncionario()
}

class DespesaTerminalHandler {
  +criar()
  +remover()
  +atualizar()
  +listar()
  +menu()
}

class GerarBalancoTerminalHandler {
  +menu()
}

class GerarRelatorioTerminalHandler {
  +menu()
}


@enduml
