@startuml
skinparam dpi 150
skinparam classAttributeIconSize 0
skinparam classFontSize 10
skinparam classFontName Courier
skinparam wrapWidth 100
top to bottom direction
skinparam linetype ortho

class LoginTerminalHandler {
  +login()
}

class OficinaTerminalHandler {
  +menu()
}

class OrdemDeServicoTerminalHandler {
  +finalizar()
  +menu()
  +listar()
  +adicionarPeca()
}

class PecaTerminalHandler {
  +criar()
  +remover()
  +atualizar()
  +entradaManual()
  +listar()
  +menu()
}

class ServicoTerminalHandler {
  +criar()
  +remover()
  +atualizar()
  +listar()
  +menu()
}

class VeiculoTerminalHandler {
  +criar()
  +remover()
  +atualizar()
  +listar()
  +buscar()
  +menu()
  +selecionarVeiculoRecebido()
  +selecionarClientePorBusca()
}

class TerminalRouter {
  +start()
  +menuFinanceiro()
}

class MainView {
  +start()
}


@enduml
