@startuml
skinparam dpi 150
skinparam classAttributeIconSize 0
skinparam classFontSize 10
skinparam classFontName Courier
skinparam wrapWidth 100
top to bottom direction
skinparam linetype ortho

class AtualizaVeiculoUseCase {
  +use()
}

class BuscarPorIdVeiculoUseCase {
  +use()
}

class CriarVeiculoUseCase {
  +use()
}

class ListaVeiculoUseCase {
  +use()
}

class RemoverVeiculoUsecase {
  +use()
}

class AtualizarAdministradorUseCase {
  +use()
}

class BuscaPorIdAdministradorUseCase {
  +use()
}

class CriarAdministradorUseCase {
  +use()
}


@enduml
