name: Build & Release

on:
  push:
    tags:
      - "v*" # Ex.: v4.1.2

permissions:
  contents: write # necessário para criar a Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Instalar e cachear o Maven + JDK 17
      - name: Setup JDK 17 + cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3) Build (inclui perfil UML para gerar SVGs)
      - name: Build (Maven package + perfil UML)
        run: mvn -B -Puml clean package

      # 4) Extrair notas da versão atual do CHANGELOG.md
      - name: Extrair notas do CHANGELOG
        id: changelog
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"   # v4.1.2
          VERSION="${TAG_NAME#v}"               # 4.1.2

          echo "Extraindo notas para $VERSION"

          NOTES=$(awk "/^### ${VERSION//./\\.}/ {flag=1; next} /^### / {flag=0} flag" CHANGELOG.md)

          # fallback se não achar
          if [ -z "$NOTES" ]; then
            NOTES="Notas não encontradas no CHANGELOG para $VERSION."
          fi

          {
            echo "release_notes<<'EOF'"
            echo "$NOTES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      # 5) Criar Release e anexar artefatos
      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.release_notes }}
          files: |
            target/*-dist.zip
            target/*-jar-with-dependencies.jar
