name: Build & Release

on:
  push:
    tags:
      - "v*" # ex.: v4.1.2

permissions:
  contents: write # criar/atualizar Release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17 + cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build (mvn -Puml)
        run: mvn -B -Puml clean package

      # (opcional) debug: liste o que foi gerado
      - name: Listar artefatos gerados
        run: ls -lh target | head -20

      - name: Extrair notas do CHANGELOG
        id: changelog
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"
          NOTES=$(awk "/^### ${VERSION//./\\.}/ {flag=1; next} /^### / {flag=0} flag" CHANGELOG.md)
          [ -z "$NOTES" ] && NOTES="Notas não encontradas no CHANGELOG para $VERSION."
          {
            echo "release_notes<<'EOF'"
            echo "$NOTES"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Criar/atualizar Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.release_notes }}
          fail_on_unmatched_files: true # falha se não achar o ZIP
          files: target/*-dist.zip # <-- só o ZIP
